# Augmentorium global configuration

general:
  log_dir: "~/.augmentorium/logs"
  log_level: "INFO"

indexer:
  polling_interval: 1.0  # seconds
  max_workers: 4
  hash_algorithm: "md5"
  ignore_patterns:
    - ".git"
    - ".augmentorium"
    - ".qodo"
    - ".venv"
    - ".mypy_cache"
    - ".pytest_cache"
    - ".idea"
    - ".vscode"
    - "node_modules"
    - "dist"
    - "build"
    - "__pycache__"
    - "*.egg-info"
    - "logs"
    - "old_code"
    - ".husky"
    - "**/.git/**"
    - "**/.augmentorium/**"
    - "**/.qodo/**"
    - "**/.venv/**"
    - "**/.mypy_cache/**"
    - "**/.pytest_cache/**"
    - "**/.idea/**"
    - "**/.vscode/**"
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/__pycache__/**"
    - "**/*.egg-info/**"
    - "**/.husky/**"
    - "**/logs/**"
    - "**/old_code/**"
    - "*.md"
    - ".Augmentorium"
    - "**/.Augmentorium/**"
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
    - "*.bmp"
    - "*.tiff"
    - "*.webp"
    - "*.svg"
    - "*.ico"
    - "*.heic"
    - "*.avif"
    - "*.jpe"
    - "*.jif"
    - "*.jfif"
    - "*.jfi"
    - "*.dib"
    - "*.tif"
    - "*.svgz"
    - "*.heif"
    - "*.apng"
    - "*.raw"
    - "*.arw"
    - "*.cr2"
    - "*.nrw"
    - "*.k25"
    - "*.jp2"
    - "*.j2k"
    - "*.jpf"
    - "*.jpx"
    - "*.jpm"
    - "*.mj2"
    - "*.ind"
    - "*.indd"
    - "*.indt"
    - "*.ai"
    - "*.eps"
    - "*.psd"
    - "*.psb"
    - "*.3fr"
    - "*.dng"
    - "*.erf"
    - "*.mef"
    - "*.mos"
    - "*.orf"
    - "*.pef"
    - "*.raf"
    - "*.rw2"
    - "*.rwl"
    - "*.sr2"
    - "*.srf"
    - "*.srw"
    - "*.x3f"

server:
  host: "localhost"
  port: 6655  # Default port for the API server
  cache_size: 100

ollama:
  # Change this to the address of your Ollama server
  base_url: "http://10.0.0.246:11434"  # Replace with your server's IP
  embedding_model: "codellama:34b"
  embedding_batch_size: 10
